### ISSUE TITLE
Please add ch 20 abstracts

### ISSUE THREAD

**Issue by vasishth** [bnicenboim/bayescogsci#1]
@bnicenboim in the Abstracts.txt file, please add ch 20 abstract.

**Comment by bnicenboim** [comment]
Is it ok?
I don't know what the guidelines for the abstracts are or where the abstracts will appear. Maybe this one is a bit more informative than the one for chapters 18-19. I don't know if it should be more similar or if I should include more information in the other abstracts.

**Comment by vasishth** [comment]
Yes this is perfect.
