### ISSUE TITLE
Boxes now seem out of context

### ISSUE THREAD

**Issue by vasishth** [bnicenboim/bayescogsci#11]
To see what became of the boxes, I looked at A7 Some important (and sometimes confusing) points.

This box now appears completely out of context in A7 and the reader has no idea what we are talking about any more. One will have to redo the boxes' titles and content to make them stand-alone. I don't know how to proceed with this but it will have to be done. Perhaps you want to distribute the labor among us (assign specific chapters to specific people, to deal with the edits of the boxes such that they provide context) @bnicenboim ?

**Comment by vasishth** [comment]
Imagine reading the book and being asked to look at A7 while reading. I don't have the internet accessible. Could become annoying.

**Comment by bnicenboim** [comment]
> This box now appears completely out of context in A7 and the reader has no idea what we are talking about any more. One will have to redo the boxes' titles and content to make them stand-alone. I don't know how to proceed with this but it will have to be done. Perhaps you want to distribute the labor among us (assign specific chapters to specific people, to deal with the edits of the boxes such that they provide context) @bnicenboim ?

Yes, I agree, and I noticed that. I'm just trying to finish the PDF part at the moment, but yes, the online material needs to be finished before we release the book or the next PDF version.

Splitting them would be good. What do you suggest?  Do you think we should remove all of them? Or leave a couple?

> Imagine reading the book and being asked to look at A7 while reading. I don't have the internet accessible. Could become annoying.

Yes, so what do we do? Maybe some of them are more annoying than others out of place.

**Comment by bnicenboim** [comment]
IMO they are fine now.
