### ISSUE TITLE
Please check my back cover text (347 words, limit is 350)

### ISSUE THREAD

**Issue by vasishth** [bnicenboim/bayescogsci#2]
I pushed the following text to the new repo:

This book introduces Bayesian data analysis and Bayesian cognitive modeling to
students and researchers in cognitive science (e.g., linguistics,
psycholinguistics, psychology, computer science), with a particular focus on
modeling data from planned experiments.  The book relies on the
probabilistic programming language Stan and the front-end R package brms. The
main text in the book only assumes that the reader is familiar with the
statistical programming language R, and has basic high school exposure to
pre-calculus mathematics; the important mathematical constructs needed for
the book are introduced in the first chapter, and all the code used is
publicly available at https://bruno.nicenboim.me/bayescogsci/.

Through this book, the reader will be able to develop a practical ability to
apply Bayesian modeling within their own fields. The book begins with an
informal introduction to foundational topics such as probability theory, and
univariate and bi-/multivariate discrete and continuous random variables. Then,
the application of Bayes' rule for statistical inference is introduced with
several simple analytical examples that require no computing software; the main
insight here is that the posterior distribution of a parameter is a compromise
between the prior and the likelihood functions. The book then gradually builds
up the regression framework to hierarchical regression modeling (aka the linear
mixed model). Along the way, there is detailed discussion about the topic of
prior selection, and developing a well-defined workflow. Later chapters
introduce the Stan programming language, and covers advanced topics such as
model comparison using Bayes factors and cross-validation for model comparison.
The last four chapters focus on implementing hierarchical computational
cognitive models within the Stan environment; several practical examples from
cognitive psychology and psycholinguistics are provided.

Bruno Nicenboim is an assistant professor in the department of Cognitive Science
and Artificial Intelligence at Tilburg University in the Netherlands, working
within the area of computational psycholinguistics. Daniel J. Schad is a
cognitive psychologists and is professor of Quantitative Methods at the Health
and Medical University in Potsdam, Germany. Shravan Vasishth is professor of
psycholinguistics at the department of Linguistics at the University of Potsdam,
Germany; he is a chartered statistician (Royal Statistical Society, UK).

**Comment by bnicenboim** [comment]
> all the code used is publicly available at https://bruno.nicenboim.me/bayescogsci/.

It sounds as if only the code is there. Can we change it to?

>the content of the book including all the code used is publicly available at https://bruno.nicenboim.me/bayescogsci/.


here, maybe "within their own fields of cognitive science"? 

> Through this book, the reader will be able to develop a practical ability to apply Bayesian modeling within their own fields. 

There is model comparison twice:

> Later chapters introduce the Stan programming language, and covers advanced topics such as model comparison using Bayes factors and cross-validation for model comparison.

We could include all the advanced topics:

> Later chapters introduce the Stan programming language, and covers advanced topics such as measurement error, meta-analysis, and model comparison using Bayes factors and cross-validation.

**Comment by bnicenboim** [comment]
ahh, sorry, I didn't see the word limit! Then my suggestions are

> Through this book, the reader will be able to develop a practical ability to apply Bayesian modeling within cognitive science.

(also agreement attraction error I think with cover)

> Later chapters introduce the Stan programming language, and cover advanced topics such as model comparison using Bayes factors and cross-validation.

> the content of the book including code is publicly available at https://bruno.nicenboim.me/bayescogsci/.

**Comment by vasishth** [comment]
> here, maybe "within their own fields of cognitive science"?

We already mentioned cognitive science, so I am trying to avoid redundant words due to the word limit. So this change I don't like.

**Comment by vasishth** [comment]
I made all the other edits that @bnicenboim suggested, but we are six words over the limit now. Maybe that's OK.

**Comment by bnicenboim** [comment]
this?

The last four chapters focus on implementing hierarchical computational cognitive models within the Stan environment; several practical examples ~from cognitive psychology and psycholinguistics~ are provided.

**Comment by vasishth** [comment]
I made some edits. We are now at 348 words. We can add two words to get exactly 350.

**Comment by bnicenboim** [comment]
We can close this, right?

**Comment by vasishth** [comment]
yes ok

**Comment by vasishth** [comment]
I changed a sentence to:

> The R Markdown source code that generated the book is
publicly available at

We had R Markdown code and ... code

**Comment by vasishth** [comment]
@bnicenboim please close if OK. I made some minor wording changes.

**Comment by bnicenboim** [comment]
I just changed this to put the cognitive models together:

Later chapters introduce the Stan programming language,
and cover advanced topics using practical examples: contrast coding, model
comparison using Bayes factors and cross-validation, hierarchical models and
reparameterization, defining custom distributions, measurement error models and
meta-analysis, and finally, some examples of cognitive models: multinomial processing trees, 
finite mixture models, and accumulator models.

Is it ok?

**Comment by vasishth** [comment]
yes
