### ISSUE TITLE
"simple regression model" in the abstracts

### ISSUE THREAD

**Issue by bnicenboim** [bnicenboim/bayescogsci#3]
An issue about the abstracts. By the way, where will they appear?

We have this:
> Chapter 3: Computational Bayesian data analysis

> This chapter introduces the basic usage of the brms library in R, focusing on a
> **simple regression model**. The chapter demonstrates how the posterior distribution
> of a parameter can be derived using sampling rather than through the analytical
> approach discussed in chapter 2. The sensitivity of the posterior to the prior
> specification is discussed, and different categories of prior (ranging from
> flat, uninformative priors to informative priors) are summarized. Two other
> important concepts introduced are prior and posterior predictive distributions.
> The influence of the likelihood function in determining the posterior is also
> discussed.
> 

Can we change **simple regression model** to a model with a normal likelihood? or a model for normally distributed data. The issue is that simple regression model sounds too much like a simple linear regression, which usually refers to a regression with a single predictor https://en.wikipedia.org/wiki/Simple_linear_regression)  (which is what we do in the next chapter)

And then I would also change this:

> Chapter 4: Bayesian regression models
> 
> Here, **we extend the simple regression model to include a predictor variable**, and
> decide on a likelihood and priors, implementing the model in brms. We introduce
> here the lognormal likelihood and show how to communicate the results of the
> modeling. Logistic regression is also introduced in this chapter, with a
> discussion of the implications of prior choice in logistic regression models;
> back-transformation of the estimated parameters from log-odds space to
> probability space is also discussed.
> 

Chapter 4: Bayesian regression models

Here, we introduce the simple regression model, including a predictor variable, and
decide on a likelihood and priors, implementing the model in brms. We introduce
 the lognormal likelihood and show how to communicate the results of the
modeling. Logistic regression is also introduced in this chapter, with a
discussion of the implications of prior choice in logistic regression models;
back-transformation of the estimated parameters from log-odds space to
probability space is also discussed.

**Comment by vasishth** [comment]
yes of course, please feel free to edit.
